# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadric_logik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('packkag', models.CharField(max_length=10)),
                ('name_subscribe', models.BooleanField()),
                ('comment', models.TextField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('date_apply', models.DateField(auto_now=True)),
            ],
        ),
    ]
