# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quadric', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quadric_logik',
            old_name='packkag',
            new_name='packag',
        ),
    ]
