# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20171115_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(to='course.Course'),
        ),
    ]
