# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
